version: "3"

tasks:
  run-server:
    cmds:
      - go run cmd/server/server.go -cmd "cni"
  build-server:
    cmds:
      - CGO_ENABLED=0 go build -o ./bin/network-runtime cmd/server/server.go
  build-docker:
    cmds:
      - docker build -t kni-network-runtime:latest -f Dockerfile .