version: "3"

tasks:
  run-server:
    cmds:
      - go run main.go
  build-server:
    cmds:
      - CGO_ENABLED=0 go build -o ./bin/network-runtime main.go
  build-docker:
    cmds:
      - docker build -t kni-network-runtime:latest -f Dockerfile .